# Generated by Django 4.0.3 on 2022-04-04 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_rename_size_room_persons_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
