# Generated by Django 4.0.3 on 2022-04-05 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_rename_persons_room_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='name',
            new_name='room_number',
        ),
    ]
