# Generated by Django 4.0.3 on 2022-04-09 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0007_restaurant_bar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurant_bar',
            options={'verbose_name': 'restaurant_bar', 'verbose_name_plural': 'restaurants_bars'},
        ),
    ]
