# Generated by Django 4.0.3 on 2022-04-09 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0008_alter_restaurant_bar_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Restaurant_Bar',
            new_name='Restaurant',
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={'verbose_name': 'restaurant', 'verbose_name_plural': 'restaurants'},
        ),
    ]
